# Generated by Django 4.2.4 on 2023-08-03 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(default='Альбом', max_length=120, verbose_name='Наименование альбома')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание альбома')),
                ('album_pub_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания альбома')),
                ('photos_quantity', models.IntegerField(verbose_name='Количество фотографий в альбоме')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['author', 'album_title'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Фамилия автора', max_length=30, verbose_name='Фамилия автора')),
                ('surname', models.CharField(default='Имя автора', max_length=30, verbose_name='Имя автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(default='Категория', max_length=30, verbose_name='Категория фотографии')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
                'ordering': ['cat_title'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фотография')),
                ('photo_pub_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.album', verbose_name='Альбом фотографии')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.category', verbose_name='Категория фотографии')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['album'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.author', verbose_name='Автор альбома'),
        ),
    ]
